import assert from 'node:assert/strict'
import { test } from 'node:test'

import { generateTypeDeclaration } from '../../../src/core/output/declaration'

import type { CollectionMeta } from '../../../src/core/output/declaration'

const meta = (name: string, typeName: string, single: boolean): CollectionMeta => ({ name, typeName, single })

test('declaration: list collection emits an array-typed const', () => {
  const types = generateTypeDeclaration([meta('posts', 'Post', false)], '../velite.config.ts')
  assert.ok(types.includes("import type __vc from '../velite.config.ts'"))
  assert.ok(types.includes("import type { Infer } from 'velite'"))
  assert.ok(types.includes('type Collections = typeof __vc.collections'))
  assert.ok(types.includes("export type Post = Infer<Collections['posts']['schema']>"))
  assert.ok(types.includes('export declare const posts: Post[]'))
})

test('declaration: single collection emits a scalar-typed const (no array)', () => {
  const types = generateTypeDeclaration([meta('site', 'Site', true)], '../velite.config.ts')
  assert.ok(types.includes("export type Site = Infer<Collections['site']['schema']>"))
  assert.ok(types.includes('export declare const site: Site'))
  assert.ok(!types.includes('site: Site[]'))
})

test('declaration: multiple collections each get a type + const', () => {
  const types = generateTypeDeclaration([meta('posts', 'Post', false), meta('site', 'Site', true)], '../velite.config.ts')
  assert.ok(types.includes('export type Post ='))
  assert.ok(types.includes('export type Site ='))
  assert.ok(types.includes('export declare const posts: Post[]'))
  assert.ok(types.includes('export declare const site: Site'))
})

test('declaration: configRelPath is prefixed with ./ when relative', () => {
  const types = generateTypeDeclaration([meta('posts', 'Post', false)], 'velite.config.ts')
  assert.ok(types.includes("import type __vc from './velite.config.ts'"), types)
})

test('declaration: leading comment marks the file as generated', () => {
  const types = generateTypeDeclaration([], '../velite.config.ts')
  assert.ok(types.startsWith('// This file is generated by Velite'))
})
