import { relative } from 'node:path'

import { collectionDataPath, collectionEntryPath, entryPath, recordFilePath, typesPath } from './layout'

import type { Collection, Collections } from '../collections'
import type { ResolvedOutput } from '../core/project'

/** A planned output write. */
export interface OutputWrite {
  readonly kind: 'record' | 'collection' | 'entry' | 'type'
  readonly path: string
  readonly content: string
}

/** A record to be written in the dev split layout. */
export interface RecordInput {
  readonly id: string
  readonly data: unknown
}

/** State carried between split-layout build runs for stale-path detection. */
export interface SplitState {
  /** All record paths written, keyed by collection. */
  readonly paths: ReadonlyMap<string, readonly string[]>
}

export interface SplitPlanResult {
  readonly writes: OutputWrite[]
  readonly state: SplitState
}

const isProduction = process.env.NODE_ENV === 'production'

const stringify = (data: unknown): string => (isProduction ? JSON.stringify(data) : JSON.stringify(data, null, 2))

/**
 * Plan the dev split layout writes for a single collection's records.
 *
 * Record file paths are derived from record identity, not content, so the same
 * record keeps a stable path across content-only changes.
 */
export const planSplitOutput = (collectionKey: string, records: readonly RecordInput[], prevState?: SplitState): SplitPlanResult => {
  const writes: OutputWrite[] = records.map(record => ({
    kind: 'record',
    path: recordFilePath(collectionKey, record.id),
    content: stringify(record.data)
  }))

  const paths = new Map<string, readonly string[]>(prevState?.paths ?? new Map())
  paths.set(
    collectionKey,
    writes.map(w => w.path)
  )

  return { writes, state: { paths } }
}

/** Plan the production single-layout write for one collection. */
export const planSingleCollection = (collectionKey: string, data: unknown): OutputWrite => ({
  kind: 'collection',
  path: collectionDataPath(collectionKey),
  content: stringify(data)
})

/**
 * Build the entry module (`index.js`) re-exporting every collection.
 *
 * In the single layout each collection is re-exported from `{key}.json`; in the
 * split layout from `collections/{key}.js`.
 */
export const planEntry = (collections: Collections, format: ResolvedOutput['format'], split: boolean): OutputWrite => {
  const lines: string[] = []
  for (const key of Object.keys(collections)) {
    const from = split ? `./collections/${key}.js` : `./${key}.json`
    if (format === 'cjs') {
      lines.push(`exports.${key} = require('${from}')`)
    } else {
      lines.push(`export { default as ${key} } from '${from}'${split ? '' : " with { type: 'json' }"}`)
    }
  }
  return { kind: 'entry', path: entryPath(), content: `// This file is generated by Velite\n\n${lines.join('\n')}\n` }
}

/**
 * Build a split-layout collection entry (`collections/{key}.js`) that imports
 * its record files and exports the array (or single record).
 */
export const planSplitCollectionEntry = (collectionKey: string, collection: Collection, recordPaths: readonly string[]): OutputWrite => {
  const imports = recordPaths.map((p, i) => `import r${i} from '../${p}' with { type: 'json' }`)
  const refs = recordPaths.map((_, i) => `r${i}`)
  const value = collection.single ? (refs[0] ?? 'undefined') : `[${refs.join(', ')}]`
  const body = imports.length > 0 ? `${imports.join('\n')}\n\n` : ''
  return {
    kind: 'collection',
    path: collectionEntryPath(collectionKey),
    content: `// This file is generated by Velite\n\n${body}export default ${value}\n`
  }
}

/**
 * Build the type declaration module (`index.d.ts`) referencing the user config.
 */
export const planTypes = (collections: Collections, configPath: string, dataDir: string): OutputWrite => {
  // path from the data dir back to the user config file
  const relPath = relative(dataDir, configPath).replaceAll('\\', '/')
  const configModPath = relPath.startsWith('.') ? relPath : `./${relPath}`
  const lines: string[] = [
    `import type __vc from '${configModPath}'`,
    "import type { InferSchema } from 'velite'",
    'type Collections = typeof __vc.collections',
    ''
  ]
  for (const [key, collection] of Object.entries(collections)) {
    lines.push(`export type ${collection.typeName} = InferSchema<Collections['${key}']['schema']>`)
    lines.push(`export declare const ${key}: ${collection.typeName}${collection.single ? '' : '[]'}`)
    lines.push('')
  }
  return { kind: 'type', path: typesPath(), content: `// This file is generated by Velite\n\n${lines.join('\n')}` }
}

/** An asset write. */
export interface AssetWrite {
  readonly sourcePath: string
  readonly outputName: string
}

/** Plan asset writes from collected asset records. */
export const planAssets = (assets: readonly AssetWrite[]): Array<{ path: string; sourcePath: string; outputName: string }> =>
  assets.map(a => ({ path: a.outputName, sourcePath: a.sourcePath, outputName: a.outputName }))

/** A complete output plan: data/type/entry writes plus asset copies. */
export interface OutputPlan {
  readonly writes: OutputWrite[]
  readonly assets: ReadonlyArray<{ path: string; sourcePath: string }>
}

export { stringify as stringifyOutput }
