import { access, copyFile, writeFile } from 'node:fs/promises'
import { join, relative } from 'node:path'

import { logger as defaultLogger } from '../runtime/logger'

import type { AssetStore } from '../assets'
import type { Collections } from '../collections'
import type { Logger } from '../runtime/logger'
import type { VeliteOutput } from './index'
import type { OutputState } from './state'

const isProduction = process.env.NODE_ENV === 'production'

type WriteFile = (path: string, content: string) => Promise<void>
type CopyFile = (source: string, destination: string) => Promise<void>
type AccessFile = (path: string) => Promise<void>

/**
 * Emit a file only if its content differs from the last write.
 *
 * Uses the supplied `OutputState.emitted` map for skip-if-same behavior. The
 * map lives on the session (or on watch state), so two independent `build()`
 * calls never share emit caches.
 */
const emit = async (
  path: string,
  content: string,
  state: OutputState,
  writeFile: WriteFile,
  accessFile: AccessFile,
  logger: Logger,
  log?: string
): Promise<void> => {
  if (state.emitted.get(path) === content) {
    try {
      await accessFile(path)
      logger.log(`skipped write '${path}' with same content`)
      return
    } catch {
      logger.log(`restoring missing '${path}' with cached content`)
    }
  }
  await writeFile(path, content)
  logger.log(log ?? `wrote '${path}' with ${content.length} bytes`)
  state.emitted.set(path, content)
}

export interface Writer {
  writeEntry(state: OutputState, dest: string, format: VeliteOutput['format'], configPath: string, collections: Collections): Promise<void>
  writeData(state: OutputState, dest: string, result: Record<string, unknown>): Promise<void>
  writeAssets(state: OutputState, dest: string, assets: AssetStore): Promise<void>
}

export interface WriterOptions {
  writeFile?: WriteFile
  copyFile?: CopyFile
  access?: AccessFile
  logger?: Logger
}

/**
 * Create an output writer service.
 */
export const createWriter = ({
  writeFile: write = writeFile,
  copyFile: copy = copyFile,
  access: accessFile = access,
  logger = defaultLogger
}: WriterOptions = {}): Writer => ({
  async writeEntry(state, dest, format, configPath, collections) {
    const begin = performance.now()

    const configModPath = relative(dest, configPath).replace(/\\/g, '/')

    const entry: string[] = []
    const dts: string[] = [`import type __vc from '${configModPath}'\n`]
    dts.push('type Collections = typeof __vc.collections\n')

    Object.entries(collections).forEach(([name, collection]) => {
      if (format === 'cjs') {
        entry.push(`exports.${name} = require('./${name}.json')`)
      } else {
        entry.push(`export { default as ${name} } from './${name}.json' with { type: 'json' }`)
      }
      dts.push(`export type ${collection.name} = Collections['${name}']['schema']['_output']`)
      dts.push(`export declare const ${name}: ${collection.name + (collection.single ? '' : '[]')}\n`)
    })

    const banner = '// This file is generated by Velite\n\n'

    const entryFile = join(dest, 'index.js')
    await emit(entryFile, banner + entry.join('\n'), state, write, accessFile, logger, `created entry file in '${entryFile}'`)

    const dtsFile = join(dest, 'index.d.ts')
    await emit(dtsFile, banner + dts.join('\n'), state, write, accessFile, logger, `created entry dts file in '${dtsFile}'`)

    logger.log(`output entry file in '${dest}'`, begin)
  },

  async writeData(state, dest, result) {
    const begin = performance.now()
    const logs: string[] = []
    await Promise.all(
      Object.entries(result).map(async ([name, data]) => {
        if (data === undefined) return
        const target = join(dest, name + '.json')
        const content = isProduction ? JSON.stringify(data) : JSON.stringify(data, null, 2)
        const length = Array.isArray(data) ? data.length : 1
        await emit(target, content, state, write, accessFile, logger, `wrote '${target}' with ${length} ${name}`)
        logs.push(`${length} ${name}`)
      })
    )
    logger.log(`output ${logs.join(', ')}`, begin)
  },

  async writeAssets(_state, dest, assets) {
    const begin = performance.now()
    const records = assets.list()
    await Promise.all(records.map(record => copy(record.sourcePath, join(dest, record.outputName))))
    logger.log(`output ${records.length} assets`, begin)
  }
})
