import { access, copyFile, writeFile } from 'node:fs/promises'
import { join, relative } from 'node:path'

import { logger as defaultLogger } from './logger'

import type { Collections, Output } from '../types'
import type { AssetStore } from './assets'
import type { Logger } from './logger'
import type { OutputState } from './output-state'

const isProduction = process.env.NODE_ENV === 'production'

export interface OutputWriterDeps {
  writeFile(path: string, content: string): Promise<void>
  copyFile(source: string, destination: string): Promise<void>
  access?(path: string): Promise<void>
  logger: Logger
}

const defaultDeps: OutputWriterDeps = { writeFile, copyFile, logger: defaultLogger }

/**
 * Emit a file only if its content differs from the last write.
 *
 * Uses the supplied `OutputState.emitted` map for skip-if-same behavior. The
 * map lives on the session (or on watch state), so two independent `build()`
 * calls never share emit caches.
 */
const emit = async (path: string, content: string, state: OutputState, deps: OutputWriterDeps, log?: string): Promise<void> => {
  if (state.emitted.get(path) === content) {
    try {
      await (deps.access ?? access)(path)
      deps.logger.log(`skipped write '${path}' with same content`)
      return
    } catch {
      deps.logger.log(`restoring missing '${path}' with cached content`)
    }
  }
  await deps.writeFile(path, content)
  deps.logger.log(log ?? `wrote '${path}' with ${content.length} bytes`)
  state.emitted.set(path, content)
}

export interface OutputWriter {
  writeEntry(dest: string, format: Output['format'], configPath: string, collections: Collections): Promise<void>
  writeData(dest: string, result: Record<string, unknown>): Promise<void>
  writeAssets(dest: string, assets: AssetStore): Promise<void>
}

/**
 * Create an output writer bound to a session-scoped output state.
 *
 * `deps` allows tests to inject fake filesystem implementations and loggers;
 * production callers should accept the default.
 */
export const createOutputWriter = (state: OutputState, deps: OutputWriterDeps = defaultDeps): OutputWriter => ({
  async writeEntry(dest, format, configPath, collections) {
    const begin = performance.now()

    const configModPath = relative(dest, configPath).replace(/\\/g, '/')

    const entry: string[] = []
    const dts: string[] = [`import type __vc from '${configModPath}'\n`]
    dts.push('type Collections = typeof __vc.collections\n')

    Object.entries(collections).forEach(([name, collection]) => {
      if (format === 'cjs') {
        entry.push(`exports.${name} = require('./${name}.json')`)
      } else {
        entry.push(`export { default as ${name} } from './${name}.json' with { type: 'json' }`)
      }
      dts.push(`export type ${collection.name} = Collections['${name}']['schema']['_output']`)
      dts.push(`export declare const ${name}: ${collection.name + (collection.single ? '' : '[]')}\n`)
    })

    const banner = '// This file is generated by Velite\n\n'

    const entryFile = join(dest, 'index.js')
    await emit(entryFile, banner + entry.join('\n'), state, deps, `created entry file in '${entryFile}'`)

    const dtsFile = join(dest, 'index.d.ts')
    await emit(dtsFile, banner + dts.join('\n'), state, deps, `created entry dts file in '${dtsFile}'`)

    deps.logger.log(`output entry file in '${dest}'`, begin)
  },

  async writeData(dest, result) {
    const begin = performance.now()
    const logs: string[] = []
    await Promise.all(
      Object.entries(result).map(async ([name, data]) => {
        if (data === undefined) return
        const target = join(dest, name + '.json')
        const content = isProduction ? JSON.stringify(data) : JSON.stringify(data, null, 2)
        const length = Array.isArray(data) ? data.length : 1
        await emit(target, content, state, deps, `wrote '${target}' with ${length} ${name}`)
        logs.push(`${length} ${name}`)
      })
    )
    deps.logger.log(`output ${logs.join(', ')}`, begin)
  },

  async writeAssets(dest, assets) {
    const begin = performance.now()
    const records = assets.list()
    await Promise.all(records.map(record => deps.copyFile(record.sourcePath, join(dest, record.outputName))))
    deps.logger.log(`output ${records.length} assets`, begin)
  }
})
