// Type declaration generation.
//
// Ported from the planTypes half of src/output/plan.ts. Emits the `index.d.ts`
// content: for each collection, a `type {TypeName} = Infer<schema>` alias plus a
// `declare const {key}` whose type is the alias (or an array of it for list
// collections). The schema is referenced through the user's config module so the
// emitted declarations track the user's schema without velite having to
// materialize the inferred type itself.

/** The collection metadata needed to emit declarations and entry modules. */
export interface CollectionMeta {
  /** Output data key (also the `declare const` name). */
  readonly name: string
  /** Generated TypeScript type name. */
  readonly typeName: string
  /** Whether the collection result is a single record instead of an array. */
  readonly single: boolean
}

/**
 * Generate the `index.d.ts` content.
 *
 * `configRelPath` is the posix-relative path from the data dir back to the user
 * config file (pre-computed by the writer so this stays pure / runtime-agnostic).
 */
export const generateTypeDeclaration = (collections: readonly CollectionMeta[], configRelPath: string): string => {
  const configModPath = configRelPath.startsWith('.') ? configRelPath : `./${configRelPath}`
  const lines: string[] = [`import type __vc from '${configModPath}'`, "import type { Infer } from 'velite'", 'type Collections = typeof __vc.collections', '']
  for (const collection of collections) {
    lines.push(`export type ${collection.typeName} = Infer<Collections['${collection.name}']['schema']>`)
    lines.push(`export declare const ${collection.name}: ${collection.typeName}${collection.single ? '' : '[]'}`)
    lines.push('')
  }
  return `// This file is generated by Velite\n\n${lines.join('\n')}`
}
