// Output planning: turn the logical build result into a list of physical
// writes (data, entry module, type declarations).
//
// Ported from src/output/plan.ts onto the new arch. Key adaptations:
// - records come from the LogicalOutput's CollectionResult.entries (each Entry
//   already carries a stable EntryId and post-prepare data), so there is no
//   separate `parsedRecords` map or index-alignment dance;
// - stale-file detection is the writer's job (via the manifest), so the old
//   SplitState is not needed here — the plan is a pure function of the current
//   output;
// - `pretty` is threaded in instead of reading process.env, keeping this module
//   runtime-agnostic.

import { generateTypeDeclaration } from './declaration'
import { collectionDataPath, collectionEntryPath, entryPath, recordFilePath, typesPath } from './layout'

import type { CollectionMeta } from './declaration'
import type { LogicalOutput } from './logical'

/** A planned output write. */
export interface OutputWrite {
  readonly kind: 'record' | 'collection' | 'entry' | 'type'
  readonly path: string
  readonly content: string
}

const stringify = (data: unknown, pretty: boolean): string => (pretty ? JSON.stringify(data, null, 2) : JSON.stringify(data))

/**
 * Plan the dev split layout record writes for a single collection's entries.
 *
 * Record file paths are derived from record identity, not content, so the same
 * record keeps a stable path across content-only changes.
 */
export const planSplitOutput = (collectionKey: string, entries: ReadonlyArray<{ id: string; data: unknown }>, pretty: boolean): OutputWrite[] =>
  entries.map(entry => ({
    kind: 'record' as const,
    path: recordFilePath(collectionKey, entry.id),
    content: stringify(entry.data, pretty)
  }))

/** Plan the production single-layout write for one collection. */
export const planSingleCollection = (collectionKey: string, data: unknown, pretty: boolean): OutputWrite => ({
  kind: 'collection',
  path: collectionDataPath(collectionKey),
  content: stringify(data, pretty)
})

/**
 * Build the entry module (`index.js`) re-exporting every collection.
 *
 * In the single layout each collection is re-exported from `{key}.json`; in the
 * split layout from `collections/{key}.js`.
 */
export const planEntry = (collections: readonly CollectionMeta[], format: 'esm' | 'cjs', split: boolean): OutputWrite => {
  const lines: string[] = []
  for (const collection of collections) {
    const from = split ? `./collections/${collection.name}.js` : `./${collection.name}.json`
    if (format === 'cjs') {
      lines.push(`exports.${collection.name} = require('${from}')`)
    } else {
      lines.push(`export { default as ${collection.name} } from '${from}'${split ? '' : " with { type: 'json' }"}`)
    }
  }
  return { kind: 'entry', path: entryPath(), content: `// This file is generated by Velite\n\n${lines.join('\n')}\n` }
}

/**
 * Build a split-layout collection entry (`collections/{key}.js`) that imports
 * its record files and exports the array (or single record).
 */
export const planSplitCollectionEntry = (collection: CollectionMeta, recordPaths: readonly string[], format: 'esm' | 'cjs'): OutputWrite => {
  const value = collection.single ? (recordPaths.length > 0 ? 'r0' : 'undefined') : `[${recordPaths.map((_, i) => `r${i}`).join(', ')}]`
  let body: string
  if (format === 'cjs') {
    const requires = recordPaths.map((p, i) => `const r${i} = require('../${p}')`)
    body = recordPaths.length > 0 ? `${requires.join('\n')}\n\n` : ''
    return {
      kind: 'collection',
      path: collectionEntryPath(collection.name),
      content: `// This file is generated by Velite\n\n${body}module.exports = ${value}\n`
    }
  }
  const imports = recordPaths.map((p, i) => `import r${i} from '../${p}' with { type: 'json' }`)
  body = imports.length > 0 ? `${imports.join('\n')}\n\n` : ''
  return {
    kind: 'collection',
    path: collectionEntryPath(collection.name),
    content: `// This file is generated by Velite\n\n${body}export default ${value}\n`
  }
}

export interface PlanWritesInput {
  readonly output: LogicalOutput
  readonly collections: readonly CollectionMeta[]
  readonly format: 'esm' | 'cjs'
  /** Posix-relative path from the data dir back to the user config file. */
  readonly configRelPath: string
  /** Pretty-print JSON data files (dev). When false, JSON is minified. */
  readonly pretty: boolean
}

/**
 * Plan all output writes for a build run.
 *
 * Combines per-collection data writes (single or split layout) with the shared
 * entry module and type declarations.
 */
export const planWrites = (input: PlanWritesInput, split: boolean): OutputWrite[] => {
  const writes: OutputWrite[] = []
  const { output, collections, format, configRelPath, pretty } = input
  for (const collection of collections) {
    const result = output.collections[collection.name]
    const entries = result?.entries ?? []
    if (split) {
      const recordWrites = planSplitOutput(collection.name, entries, pretty)
      writes.push(...recordWrites)
      writes.push(
        planSplitCollectionEntry(
          collection,
          recordWrites.map(w => w.path),
          format
        )
      )
    } else {
      const data = collection.single ? (entries[0]?.data ?? null) : entries.map(entry => entry.data)
      writes.push(planSingleCollection(collection.name, data, pretty))
    }
  }
  writes.push(planEntry(collections, format, split))
  writes.push({ kind: 'type', path: typesPath(), content: generateTypeDeclaration(collections, configRelPath) })
  return writes
}
