// https://github.com/sindresorhus/irregular-plurals/blob/main/irregular-plurals.json
const plurals = {
  addendum: 'addenda',
  aircraft: 'aircraft',
  alga: 'algae',
  alumna: 'alumnae',
  alumnus: 'alumni',
  alveolus: 'alveoli',
  amoeba: 'amoebae',
  analysis: 'analyses',
  antenna: 'antennae',
  antithesis: 'antitheses',
  apex: 'apices',
  appendix: 'appendices',
  automaton: 'automata',
  axis: 'axes',
  bacillus: 'bacilli',
  bacterium: 'bacteria',
  baculum: 'bacula',
  barracks: 'barracks',
  basis: 'bases',
  beau: 'beaux',
  bison: 'bison',
  buffalo: 'buffalo',
  bureau: 'bureaus',
  cactus: 'cacti',
  calf: 'calves',
  carcinoma: 'carcinomata',
  carp: 'carp',
  census: 'censuses',
  chassis: 'chassis',
  cherub: 'cherubim',
  child: 'children',
  château: 'châteaus',
  cloaca: 'cloacae',
  cod: 'cod',
  codex: 'codices',
  concerto: 'concerti',
  consortium: 'consortia',
  corpus: 'corpora',
  crisis: 'crises',
  criterion: 'criteria',
  curriculum: 'curricula',
  cystoma: 'cystomata',
  datum: 'data',
  deer: 'deer',
  diagnosis: 'diagnoses',
  die: 'dice',
  dwarf: 'dwarfs',
  echo: 'echoes',
  elf: 'elves',
  elk: 'elk',
  ellipsis: 'ellipses',
  embargo: 'embargoes',
  emphasis: 'emphases',
  erratum: 'errata',
  'faux pas': 'faux pas',
  fez: 'fezes',
  firmware: 'firmware',
  fish: 'fish',
  focus: 'foci',
  foot: 'feet',
  formula: 'formulae',
  fungus: 'fungi',
  gallows: 'gallows',
  genus: 'genera',
  glomerulus: 'glomeruli',
  goose: 'geese',
  graffito: 'graffiti',
  grouse: 'grouse',
  half: 'halves',
  hamulus: 'hamuli',
  hero: 'heroes',
  hippopotamus: 'hippopotami',
  hoof: 'hooves',
  hovercraft: 'hovercraft',
  hypothesis: 'hypotheses',
  iliac: 'ilia',
  incubus: 'incubi',
  index: 'indices',
  interstitium: 'interstitia',
  kakapo: 'kakapo',
  knife: 'knives',
  larva: 'larvae',
  leaf: 'leaves',
  libretto: 'libretti',
  life: 'lives',
  loaf: 'loaves',
  loculus: 'loculi',
  locus: 'loci',
  louse: 'lice',
  man: 'men',
  matrix: 'matrices',
  means: 'means',
  measles: 'measles',
  media: 'media',
  medium: 'media',
  memorandum: 'memoranda',
  millennium: 'millennia',
  minutia: 'minutiae',
  moose: 'moose',
  mouse: 'mice',
  nebula: 'nebulae',
  nemesis: 'nemeses',
  neurosis: 'neuroses',
  news: 'news',
  nucleolus: 'nucleoli',
  nucleus: 'nuclei',
  oasis: 'oases',
  occiput: 'occipita',
  offspring: 'offspring',
  omphalos: 'omphaloi',
  opus: 'opera',
  ovum: 'ova',
  ox: 'oxen',
  paralysis: 'paralyses',
  parenthesis: 'parentheses',
  person: 'people',
  phenomenon: 'phenomena',
  phylum: 'phyla',
  pike: 'pike',
  polyhedron: 'polyhedra',
  potato: 'potatoes',
  primus: 'primi',
  prognosis: 'prognoses',
  quiz: 'quizzes',
  radius: 'radii',
  referendum: 'referenda',
  salmon: 'salmon',
  scarf: 'scarves',
  scrotum: 'scrota',
  self: 'selves',
  seminoma: 'seminomata',
  series: 'series',
  sheep: 'sheep',
  shelf: 'shelves',
  shrimp: 'shrimp',
  simulacrum: 'simulacra',
  soliloquy: 'soliloquies',
  spacecraft: 'spacecraft',
  species: 'species',
  spectrum: 'spectra',
  squid: 'squid',
  stimulus: 'stimuli',
  stratum: 'strata',
  swine: 'swine',
  syconium: 'syconia',
  syllabus: 'syllabi',
  symposium: 'symposia',
  synopsis: 'synopses',
  synthesis: 'syntheses',
  tableau: 'tableaus',
  testis: 'testes',
  that: 'those',
  thesis: 'theses',
  thief: 'thieves',
  this: 'these',
  thrombus: 'thrombi',
  tomato: 'tomatoes',
  tooth: 'teeth',
  torus: 'tori',
  trout: 'trout',
  tuna: 'tuna',
  umbilicus: 'umbilici',
  uterus: 'uteri',
  vertebra: 'vertebrae',
  vertex: 'vertices',
  veto: 'vetoes',
  vita: 'vitae',
  vortex: 'vortices',
  watercraft: 'watercraft',
  wharf: 'wharves',
  wife: 'wives',
  wolf: 'wolves',
  woman: 'women'
}

const singulars = new Map(Object.entries(plurals).map(([key, value]) => [value, key]))

// https://github.com/sindresorhus/plur/blob/main/index.js
// TODO: add more rules
export const singularTypeName = (name: string) => {
  name = name.toLowerCase()
  if (singulars.has(name)) {
    const plural = singulars.get(name)!
    return plural.charAt(0).toUpperCase() + plural.slice(1)
  }
  if (name.endsWith('ies')) {
    return name.charAt(0).toUpperCase() + name.slice(1, -3) + 'y'
  }
  if (name.endsWith('es')) {
    return name.charAt(0).toUpperCase() + name.slice(1, -2)
  }
  if (name.endsWith('s')) {
    return name.charAt(0).toUpperCase() + name.slice(1, -1)
  }
}
