// Builtin schema barrel. Each builtin lives in its own file; this module
// re-exports them so `s.ts` can spread `...builtins` onto the zod namespace.

export { excerpt } from './excerpt'
export type { ExcerptSchemaOptions } from './excerpt'
export { file } from './file'
export type { FileSchemaOptions } from './file'
export { image } from './image'
export type { ImageData, ImageSchemaOptions } from './image'
export { isoDate } from './iso-date'
export { markdown } from './markdown'
export type { MarkdownSchemaOptions } from './markdown'
export { mdx } from './mdx'
export type { MdxSchemaOptions } from './mdx'
export { metadata } from './metadata'
export type { Metadata } from './metadata'
export { path } from './path-schema'
export type { PathSchemaOptions } from './path-schema'
export { raw } from './raw'
export { toc } from './toc'
export { slug, unique } from './unique'
